### PR TITLE
Make github build and publish the container

### PR DESCRIPTION
**Pull request by ThoFrank**
GitHub Actions make it really easy to add a ci which builds and uploads the built container. And it's free.

### CODE REVIEW

**Comment by ThoFrank** [comment]
One small note: the actions will only run on commits where they are already included. So no images for currently released versions

**Comment by coleifer** [comment]
I've never tried building docker images so I pulled in your changes one at a time to check them out but it looks like they're working (!). Thank you for the suggestion and for the patch.

**Comment by coleifer** [comment]
https://github.com/coleifer/sqlite-web/actions/runs/11973507978/job/33382565582

**Comment by ThoFrank** [comment]
Thanks for giving it a try. Hope the release workflow will be working, too.

**Pull request closed without merging**
