### PR TITLE
Allow deleting and editing items in content table

### PR DESCRIPTION
**Pull request by bmwant**
## Rationale
We can change a structure of a table itself and it would be nice to modify rows as well.

## Changes
* Allow drop rows
* Allow update rows
* Add autoreload for templates when `--debug` flag is provided
* Some codestyle updates according to pep8

## Screenshots
actions_scrn
edit_item_scrn

### CODE REVIEW

**Comment by bmwant** [comment]
@coleifer do you think it's something that might be included here?
I plan to work on "adding new row" feature as well and will test it more thoroughly then.

**Comment by coleifer** [comment]
While this is nice, there are a couple issues. SQLite tables may not always have a rowid (if declared WITHOUT ROWID, for example). My impression is that this would break such tables.

Additionally, adding editing capabilities entails a lot more than what has been implemented:

* Validation -- this is hard to get right.
* Appropriate fields for columns, e.g. a date widget, a date+time widget, a checkbox for boolean fields. What about BLOB fields? They aren't text per-se. Foreign keys or multi-column foreign keys? NULL values versus empty strings?
* Reporting errors to users when there is a problem with the data.

Rather than deal with these, the UI supports executing INSERT and UPDATE queries using the "QUERY" tab.

**Comment by patarapolw** [comment]
It is possible to right-click to show `executing INSERT and UPDATE queries` based on row_id, and column header name? Then show jQuery UI dialog. This might make it easier to validate.

It is also possible to disable some of the troublesome right clicks.

So that I don't have to switch tabs just to edit the data.

**Comment by Spandan-Madan** [comment]
Was this merged into the main branch? I would love the functionality to delete rows if not edit or add. Is there a way?

Thanks!

**Pull request closed without merging**
